[package]
name = "cargonaut-ui-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "ratatui-based renderer for Cargonaut."

[dependencies]
cargonaut-core = { path = "../cargonaut-core" }
cargonaut-vfs = { path = "../cargonaut-vfs" }
ratatui = { workspace = true }
crossterm = { workspace = true, features = ["event-stream"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
smol_str = { workspace = true }
